/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sample.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.sample.service.model.SampleData;
import com.liferay.sample.service.model.SampleDataModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SampleData service. Represents a row in the &quot;liferay_SampleData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SampleDataModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SampleDataImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SampleDataImpl
 * @generated
 */
@JSON(strict = true)
public class SampleDataModelImpl
	extends BaseModelImpl<SampleData> implements SampleDataModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sample data model instance should use the <code>SampleData</code> interface instead.
	 */
	public static final String TABLE_NAME = "liferay_SampleData";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"sampleDataId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"firstName", Types.VARCHAR}, {"lastName", Types.VARCHAR},
		{"mobileNumber", Types.VARCHAR}, {"email", Types.VARCHAR},
		{"product", Types.VARCHAR}, {"expiryDate", Types.TIMESTAMP},
		{"hobbies", Types.VARCHAR}, {"consent", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("sampleDataId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("firstName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("mobileNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("product", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("expiryDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("hobbies", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("consent", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table liferay_SampleData (uuid_ VARCHAR(75) null,sampleDataId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,firstName VARCHAR(75) null,lastName VARCHAR(75) null,mobileNumber VARCHAR(75) null,email VARCHAR(75) null,product VARCHAR(75) null,expiryDate DATE null,hobbies VARCHAR(75) null,consent VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table liferay_SampleData";

	public static final String ORDER_BY_JPQL =
		" ORDER BY sampleData.firstName ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY liferay_SampleData.firstName ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FIRSTNAME_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public SampleDataModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _sampleDataId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSampleDataId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _sampleDataId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SampleData.class;
	}

	@Override
	public String getModelClassName() {
		return SampleData.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SampleData, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SampleData, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SampleData, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((SampleData)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SampleData, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SampleData, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SampleData)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SampleData, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SampleData, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<SampleData, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<SampleData, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<SampleData, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<SampleData, Object>>();
		Map<String, BiConsumer<SampleData, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<SampleData, ?>>();

		attributeGetterFunctions.put("uuid", SampleData::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<SampleData, String>)SampleData::setUuid);
		attributeGetterFunctions.put(
			"sampleDataId", SampleData::getSampleDataId);
		attributeSetterBiConsumers.put(
			"sampleDataId",
			(BiConsumer<SampleData, Long>)SampleData::setSampleDataId);
		attributeGetterFunctions.put("groupId", SampleData::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<SampleData, Long>)SampleData::setGroupId);
		attributeGetterFunctions.put("companyId", SampleData::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<SampleData, Long>)SampleData::setCompanyId);
		attributeGetterFunctions.put("userId", SampleData::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<SampleData, Long>)SampleData::setUserId);
		attributeGetterFunctions.put("userName", SampleData::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<SampleData, String>)SampleData::setUserName);
		attributeGetterFunctions.put("createDate", SampleData::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<SampleData, Date>)SampleData::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", SampleData::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<SampleData, Date>)SampleData::setModifiedDate);
		attributeGetterFunctions.put("firstName", SampleData::getFirstName);
		attributeSetterBiConsumers.put(
			"firstName",
			(BiConsumer<SampleData, String>)SampleData::setFirstName);
		attributeGetterFunctions.put("lastName", SampleData::getLastName);
		attributeSetterBiConsumers.put(
			"lastName",
			(BiConsumer<SampleData, String>)SampleData::setLastName);
		attributeGetterFunctions.put(
			"mobileNumber", SampleData::getMobileNumber);
		attributeSetterBiConsumers.put(
			"mobileNumber",
			(BiConsumer<SampleData, String>)SampleData::setMobileNumber);
		attributeGetterFunctions.put("email", SampleData::getEmail);
		attributeSetterBiConsumers.put(
			"email", (BiConsumer<SampleData, String>)SampleData::setEmail);
		attributeGetterFunctions.put("product", SampleData::getProduct);
		attributeSetterBiConsumers.put(
			"product", (BiConsumer<SampleData, String>)SampleData::setProduct);
		attributeGetterFunctions.put("expiryDate", SampleData::getExpiryDate);
		attributeSetterBiConsumers.put(
			"expiryDate",
			(BiConsumer<SampleData, Date>)SampleData::setExpiryDate);
		attributeGetterFunctions.put("hobbies", SampleData::getHobbies);
		attributeSetterBiConsumers.put(
			"hobbies", (BiConsumer<SampleData, String>)SampleData::setHobbies);
		attributeGetterFunctions.put("consent", SampleData::getConsent);
		attributeSetterBiConsumers.put(
			"consent", (BiConsumer<SampleData, String>)SampleData::setConsent);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getSampleDataId() {
		return _sampleDataId;
	}

	@Override
	public void setSampleDataId(long sampleDataId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sampleDataId = sampleDataId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getFirstName() {
		if (_firstName == null) {
			return "";
		}
		else {
			return _firstName;
		}
	}

	@Override
	public void setFirstName(String firstName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_firstName = firstName;
	}

	@JSON
	@Override
	public String getLastName() {
		if (_lastName == null) {
			return "";
		}
		else {
			return _lastName;
		}
	}

	@Override
	public void setLastName(String lastName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lastName = lastName;
	}

	@JSON
	@Override
	public String getMobileNumber() {
		if (_mobileNumber == null) {
			return "";
		}
		else {
			return _mobileNumber;
		}
	}

	@Override
	public void setMobileNumber(String mobileNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mobileNumber = mobileNumber;
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_email = email;
	}

	@JSON
	@Override
	public String getProduct() {
		if (_product == null) {
			return "";
		}
		else {
			return _product;
		}
	}

	@Override
	public void setProduct(String product) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_product = product;
	}

	@JSON
	@Override
	public Date getExpiryDate() {
		return _expiryDate;
	}

	@Override
	public void setExpiryDate(Date expiryDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_expiryDate = expiryDate;
	}

	@JSON
	@Override
	public String getHobbies() {
		if (_hobbies == null) {
			return "";
		}
		else {
			return _hobbies;
		}
	}

	@Override
	public void setHobbies(String hobbies) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_hobbies = hobbies;
	}

	@JSON
	@Override
	public String getConsent() {
		if (_consent == null) {
			return "";
		}
		else {
			return _consent;
		}
	}

	@Override
	public void setConsent(String consent) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_consent = consent;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(SampleData.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), SampleData.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SampleData toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SampleData>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SampleDataImpl sampleDataImpl = new SampleDataImpl();

		sampleDataImpl.setUuid(getUuid());
		sampleDataImpl.setSampleDataId(getSampleDataId());
		sampleDataImpl.setGroupId(getGroupId());
		sampleDataImpl.setCompanyId(getCompanyId());
		sampleDataImpl.setUserId(getUserId());
		sampleDataImpl.setUserName(getUserName());
		sampleDataImpl.setCreateDate(getCreateDate());
		sampleDataImpl.setModifiedDate(getModifiedDate());
		sampleDataImpl.setFirstName(getFirstName());
		sampleDataImpl.setLastName(getLastName());
		sampleDataImpl.setMobileNumber(getMobileNumber());
		sampleDataImpl.setEmail(getEmail());
		sampleDataImpl.setProduct(getProduct());
		sampleDataImpl.setExpiryDate(getExpiryDate());
		sampleDataImpl.setHobbies(getHobbies());
		sampleDataImpl.setConsent(getConsent());

		sampleDataImpl.resetOriginalValues();

		return sampleDataImpl;
	}

	@Override
	public SampleData cloneWithOriginalValues() {
		SampleDataImpl sampleDataImpl = new SampleDataImpl();

		sampleDataImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		sampleDataImpl.setSampleDataId(
			this.<Long>getColumnOriginalValue("sampleDataId"));
		sampleDataImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		sampleDataImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		sampleDataImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		sampleDataImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		sampleDataImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		sampleDataImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		sampleDataImpl.setFirstName(
			this.<String>getColumnOriginalValue("firstName"));
		sampleDataImpl.setLastName(
			this.<String>getColumnOriginalValue("lastName"));
		sampleDataImpl.setMobileNumber(
			this.<String>getColumnOriginalValue("mobileNumber"));
		sampleDataImpl.setEmail(this.<String>getColumnOriginalValue("email"));
		sampleDataImpl.setProduct(
			this.<String>getColumnOriginalValue("product"));
		sampleDataImpl.setExpiryDate(
			this.<Date>getColumnOriginalValue("expiryDate"));
		sampleDataImpl.setHobbies(
			this.<String>getColumnOriginalValue("hobbies"));
		sampleDataImpl.setConsent(
			this.<String>getColumnOriginalValue("consent"));

		return sampleDataImpl;
	}

	@Override
	public int compareTo(SampleData sampleData) {
		int value = 0;

		value = getFirstName().compareTo(sampleData.getFirstName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SampleData)) {
			return false;
		}

		SampleData sampleData = (SampleData)object;

		long primaryKey = sampleData.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SampleData> toCacheModel() {
		SampleDataCacheModel sampleDataCacheModel = new SampleDataCacheModel();

		sampleDataCacheModel.uuid = getUuid();

		String uuid = sampleDataCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			sampleDataCacheModel.uuid = null;
		}

		sampleDataCacheModel.sampleDataId = getSampleDataId();

		sampleDataCacheModel.groupId = getGroupId();

		sampleDataCacheModel.companyId = getCompanyId();

		sampleDataCacheModel.userId = getUserId();

		sampleDataCacheModel.userName = getUserName();

		String userName = sampleDataCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			sampleDataCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			sampleDataCacheModel.createDate = createDate.getTime();
		}
		else {
			sampleDataCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			sampleDataCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			sampleDataCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		sampleDataCacheModel.firstName = getFirstName();

		String firstName = sampleDataCacheModel.firstName;

		if ((firstName != null) && (firstName.length() == 0)) {
			sampleDataCacheModel.firstName = null;
		}

		sampleDataCacheModel.lastName = getLastName();

		String lastName = sampleDataCacheModel.lastName;

		if ((lastName != null) && (lastName.length() == 0)) {
			sampleDataCacheModel.lastName = null;
		}

		sampleDataCacheModel.mobileNumber = getMobileNumber();

		String mobileNumber = sampleDataCacheModel.mobileNumber;

		if ((mobileNumber != null) && (mobileNumber.length() == 0)) {
			sampleDataCacheModel.mobileNumber = null;
		}

		sampleDataCacheModel.email = getEmail();

		String email = sampleDataCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			sampleDataCacheModel.email = null;
		}

		sampleDataCacheModel.product = getProduct();

		String product = sampleDataCacheModel.product;

		if ((product != null) && (product.length() == 0)) {
			sampleDataCacheModel.product = null;
		}

		Date expiryDate = getExpiryDate();

		if (expiryDate != null) {
			sampleDataCacheModel.expiryDate = expiryDate.getTime();
		}
		else {
			sampleDataCacheModel.expiryDate = Long.MIN_VALUE;
		}

		sampleDataCacheModel.hobbies = getHobbies();

		String hobbies = sampleDataCacheModel.hobbies;

		if ((hobbies != null) && (hobbies.length() == 0)) {
			sampleDataCacheModel.hobbies = null;
		}

		sampleDataCacheModel.consent = getConsent();

		String consent = sampleDataCacheModel.consent;

		if ((consent != null) && (consent.length() == 0)) {
			sampleDataCacheModel.consent = null;
		}

		return sampleDataCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SampleData, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SampleData, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SampleData, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((SampleData)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SampleData>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					SampleData.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _sampleDataId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _firstName;
	private String _lastName;
	private String _mobileNumber;
	private String _email;
	private String _product;
	private Date _expiryDate;
	private String _hobbies;
	private String _consent;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<SampleData, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SampleData)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("sampleDataId", _sampleDataId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("firstName", _firstName);
		_columnOriginalValues.put("lastName", _lastName);
		_columnOriginalValues.put("mobileNumber", _mobileNumber);
		_columnOriginalValues.put("email", _email);
		_columnOriginalValues.put("product", _product);
		_columnOriginalValues.put("expiryDate", _expiryDate);
		_columnOriginalValues.put("hobbies", _hobbies);
		_columnOriginalValues.put("consent", _consent);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("sampleDataId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("firstName", 256L);

		columnBitmasks.put("lastName", 512L);

		columnBitmasks.put("mobileNumber", 1024L);

		columnBitmasks.put("email", 2048L);

		columnBitmasks.put("product", 4096L);

		columnBitmasks.put("expiryDate", 8192L);

		columnBitmasks.put("hobbies", 16384L);

		columnBitmasks.put("consent", 32768L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SampleData _escapedModel;

}