/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sample.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the SampleData service. Represents a row in the &quot;liferay_SampleData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.sample.service.model.impl.SampleDataModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.sample.service.model.impl.SampleDataImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SampleData
 * @generated
 */
@ProviderType
public interface SampleDataModel
	extends BaseModel<SampleData>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sample data model instance should use the {@link SampleData} interface instead.
	 */

	/**
	 * Returns the primary key of this sample data.
	 *
	 * @return the primary key of this sample data
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sample data.
	 *
	 * @param primaryKey the primary key of this sample data
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this sample data.
	 *
	 * @return the uuid of this sample data
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this sample data.
	 *
	 * @param uuid the uuid of this sample data
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the sample data ID of this sample data.
	 *
	 * @return the sample data ID of this sample data
	 */
	public long getSampleDataId();

	/**
	 * Sets the sample data ID of this sample data.
	 *
	 * @param sampleDataId the sample data ID of this sample data
	 */
	public void setSampleDataId(long sampleDataId);

	/**
	 * Returns the group ID of this sample data.
	 *
	 * @return the group ID of this sample data
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this sample data.
	 *
	 * @param groupId the group ID of this sample data
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this sample data.
	 *
	 * @return the company ID of this sample data
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this sample data.
	 *
	 * @param companyId the company ID of this sample data
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this sample data.
	 *
	 * @return the user ID of this sample data
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this sample data.
	 *
	 * @param userId the user ID of this sample data
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this sample data.
	 *
	 * @return the user uuid of this sample data
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this sample data.
	 *
	 * @param userUuid the user uuid of this sample data
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this sample data.
	 *
	 * @return the user name of this sample data
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this sample data.
	 *
	 * @param userName the user name of this sample data
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this sample data.
	 *
	 * @return the create date of this sample data
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this sample data.
	 *
	 * @param createDate the create date of this sample data
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this sample data.
	 *
	 * @return the modified date of this sample data
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this sample data.
	 *
	 * @param modifiedDate the modified date of this sample data
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the first name of this sample data.
	 *
	 * @return the first name of this sample data
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this sample data.
	 *
	 * @param firstName the first name of this sample data
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this sample data.
	 *
	 * @return the last name of this sample data
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this sample data.
	 *
	 * @param lastName the last name of this sample data
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the mobile number of this sample data.
	 *
	 * @return the mobile number of this sample data
	 */
	@AutoEscape
	public String getMobileNumber();

	/**
	 * Sets the mobile number of this sample data.
	 *
	 * @param mobileNumber the mobile number of this sample data
	 */
	public void setMobileNumber(String mobileNumber);

	/**
	 * Returns the email of this sample data.
	 *
	 * @return the email of this sample data
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this sample data.
	 *
	 * @param email the email of this sample data
	 */
	public void setEmail(String email);

	/**
	 * Returns the product of this sample data.
	 *
	 * @return the product of this sample data
	 */
	@AutoEscape
	public String getProduct();

	/**
	 * Sets the product of this sample data.
	 *
	 * @param product the product of this sample data
	 */
	public void setProduct(String product);

	/**
	 * Returns the expiry date of this sample data.
	 *
	 * @return the expiry date of this sample data
	 */
	public Date getExpiryDate();

	/**
	 * Sets the expiry date of this sample data.
	 *
	 * @param expiryDate the expiry date of this sample data
	 */
	public void setExpiryDate(Date expiryDate);

	/**
	 * Returns the hobbies of this sample data.
	 *
	 * @return the hobbies of this sample data
	 */
	@AutoEscape
	public String getHobbies();

	/**
	 * Sets the hobbies of this sample data.
	 *
	 * @param hobbies the hobbies of this sample data
	 */
	public void setHobbies(String hobbies);

	/**
	 * Returns the consent of this sample data.
	 *
	 * @return the consent of this sample data
	 */
	@AutoEscape
	public String getConsent();

	/**
	 * Sets the consent of this sample data.
	 *
	 * @param consent the consent of this sample data
	 */
	public void setConsent(String consent);

	@Override
	public SampleData cloneWithOriginalValues();

}